const cards = [
  {
    id: 1,
    name: 'Clubs 1',
    imageUrl: './assets/cards/card-clubs-1.png',
    publicImageUrl: '/images/cards/card-clubs-1.png',
  },
  {
    id: 2,
    name: 'Diamonds 1',
    imageUrl: './assets/cards/card-diamonds-1.png',
    publicImageUrl: '/images/cards/card-diamonds-1.png',
  },
  {
    id: 3,
    name: 'Hearts 1',
    imageUrl: './assets/cards/card-hearts-1.png',
    publicImageUrl: '/images/cards/card-hearts-1.png',
  },
  {
    id: 4,
    name: 'Spades 1',
    imageUrl: './assets/cards/card-spades-1.png',
    publicImageUrl: '/images/cards/card-spades-1.png',
  },
  {
    id: 5,
    name: 'Clubs 2',
    imageUrl: './assets/cards/card-clubs-2.png',
    publicImageUrl: '/images/cards/card-clubs-2.png',
  },
  {
    id: 6,
    name: 'Diamonds 2',
    imageUrl: './assets/cards/card-diamonds-2.png',
    publicImageUrl: '/images/cards/card-diamonds-2.png',
  },
  {
    id: 7,
    name: 'Hearts 2',
    imageUrl: './assets/cards/card-hearts-2.png',
    publicImageUrl: '/images/cards/card-hearts-2.png',
  },
  {
    id: 8,
    name: 'Spades 2',
    imageUrl: './assets/cards/card-spades-2.png',
    publicImageUrl: '/images/cards/card-spades-2.png',
  },
  {
    id: 9,
    name: 'Clubs 3',
    imageUrl: './assets/cards/card-clubs-3.png',
    publicImageUrl: '/images/cards/card-clubs-3.png',
  },
  {
    id: 10,
    name: 'Diamonds 3',
    imageUrl: './assets/cards/card-diamonds-3.png',
    publicImageUrl: '/images/cards/card-diamonds-3.png',
  },
  {
    id: 11,
    name: 'Hearts 3',
    imageUrl: './assets/cards/card-hearts-3.png',
    publicImageUrl: '/images/cards/card-hearts-3.png',
  },
  {
    id: 12,
    name: 'Spades 3',
    imageUrl: './assets/cards/card-spades-3.png',
    publicImageUrl: '/images/cards/card-spades-3.png',
  },
  {
    id: 13,
    name: 'Clubs 4',
    imageUrl: './assets/cards/card-clubs-4.png',
    publicImageUrl: '/images/cards/card-clubs-4.png',
  },
  {
    id: 14,
    name: 'Diamonds 4',
    imageUrl: './assets/cards/card-diamonds-4.png',
    publicImageUrl: '/images/cards/card-diamonds-4.png',
  },
  {
    id: 15,
    name: 'Hearts 4',
    imageUrl: './assets/cards/card-hearts-4.png',
    publicImageUrl: '/images/cards/card-hearts-4.png',
  },
  {
    id: 16,
    name: 'Spades 4',
    imageUrl: './assets/cards/card-spades-4.png',
    publicImageUrl: '/images/cards/card-spades-4.png',
  },
  {
    id: 17,
    name: 'Clubs 5',
    imageUrl: './assets/cards/card-clubs-5.png',
    publicImageUrl: '/images/cards/card-clubs-5.png',
  },
  {
    id: 18,
    name: 'Diamonds 5',
    imageUrl: './assets/cards/card-diamonds-5.png',
    publicImageUrl: '/images/cards/card-diamonds-5.png',
  },
  {
    id: 19,
    name: 'Hearts 5',
    imageUrl: './assets/cards/card-hearts-5.png',
    publicImageUrl: '/images/cards/card-hearts-5.png',
  },
  {
    id: 20,
    name: 'Spades 5',
    imageUrl: './assets/cards/card-spades-5.png',
    publicImageUrl: '/images/cards/card-spades-5.png',
  },
  {
    id: 21,
    name: 'Clubs 6',
    imageUrl: './assets/cards/card-clubs-6.png',
    publicImageUrl: '/images/cards/card-clubs-6.png',
  },
  {
    id: 22,
    name: 'Diamonds 6',
    imageUrl: './assets/cards/card-diamonds-6.png',
    publicImageUrl: '/images/cards/card-diamonds-6.png',
  },
  {
    id: 23,
    name: 'Hearts 6',
    imageUrl: './assets/cards/card-hearts-6.png',
    publicImageUrl: '/images/cards/card-hearts-6.png',
  },
  {
    id: 24,
    name: 'Spades 6',
    imageUrl: './assets/cards/card-spades-6.png',
    publicImageUrl: '/images/cards/card-spades-6.png',
  },
  {
    id: 25,
    name: 'Clubs 7',
    imageUrl: './assets/cards/card-clubs-7.png',
    publicImageUrl: '/images/cards/card-clubs-7.png',
  },
  {
    id: 26,
    name: 'Diamonds 7',
    imageUrl: './assets/cards/card-diamonds-7.png',
    publicImageUrl: '/images/cards/card-diamonds-7.png',
  },
  {
    id: 27,
    name: 'Hearts 7',
    imageUrl: './assets/cards/card-hearts-7.png',
    publicImageUrl: '/images/cards/card-hearts-7.png',
  },
  {
    id: 28,
    name: 'Spades 7',
    imageUrl: './assets/cards/card-spades-7.png',
    publicImageUrl: '/images/cards/card-spades-7.png',
  },
  {
    id: 29,
    name: 'Clubs 8',
    imageUrl: './assets/cards/card-clubs-8.png',
    publicImageUrl: '/images/cards/card-clubs-8.png',
  },
  {
    id: 30,
    name: 'Diamonds 8',
    imageUrl: './assets/cards/card-diamonds-8.png',
    publicImageUrl: '/images/cards/card-diamonds-8.png',
  },
  {
    id: 31,
    name: 'Hearts 8',
    imageUrl: './assets/cards/card-hearts-8.png',
    publicImageUrl: '/images/cards/card-hearts-8.png',
  },
  {
    id: 32,
    name: 'Spades 8',
    imageUrl: './assets/cards/card-spades-8.png',
    publicImageUrl: '/images/cards/card-spades-8.png',
  },
  {
    id: 33,
    name: 'Clubs 9',
    imageUrl: './assets/cards/card-clubs-9.png',
    publicImageUrl: '/images/cards/card-clubs-9.png',
  },
  {
    id: 34,
    name: 'Diamonds 9',
    imageUrl: './assets/cards/card-diamonds-9.png',
    publicImageUrl: '/images/cards/card-diamonds-9.png',
  },
  {
    id: 35,
    name: 'Hearts 9',
    imageUrl: './assets/cards/card-hearts-9.png',
    publicImageUrl: '/images/cards/card-hearts-9.png',
  },
  {
    id: 36,
    name: 'Spades 9',
    imageUrl: './assets/cards/card-spades-9.png',
    publicImageUrl: '/images/cards/card-spades-9.png',
  },
  {
    id: 37,
    name: 'Clubs 10',
    imageUrl: './assets/cards/card-clubs-10.png',
    publicImageUrl: '/images/cards/card-clubs-10.png',
  },
  {
    id: 38,
    name: 'Diamonds 10',
    imageUrl: './assets/cards/card-diamonds-10.png',
    publicImageUrl: '/images/cards/card-diamonds-10.png',
  },
  {
    id: 39,
    name: 'Hearts 10',
    imageUrl: './assets/cards/card-hearts-10.png',
    publicImageUrl: '/images/cards/card-hearts-10.png',
  },
  {
    id: 40,
    name: 'Spades 10',
    imageUrl: './assets/cards/card-spades-10.png',
    publicImageUrl: '/images/cards/card-spades-10.png',
  },
  {
    id: 41,
    name: 'Clubs 11',
    imageUrl: './assets/cards/card-clubs-11.png',
    publicImageUrl: '/images/cards/card-clubs-11.png',
  },
  {
    id: 42,
    name: 'Diamonds 11',
    imageUrl: './assets/cards/card-diamonds-11.png',
    publicImageUrl: '/images/cards/card-diamonds-11.png',
  },
  {
    id: 43,
    name: 'Hearts 11',
    imageUrl: './assets/cards/card-hearts-11.png',
    publicImageUrl: '/images/cards/card-hearts-11.png',
  },
  {
    id: 44,
    name: 'Spades 11',
    imageUrl: './assets/cards/card-spades-11.png',
    publicImageUrl: '/images/cards/card-spades-11.png',
  },
  {
    id: 45,
    name: 'Clubs 12',
    imageUrl: './assets/cards/card-clubs-12.png',
    publicImageUrl: '/images/cards/card-clubs-12.png',
  },
  {
    id: 46,
    name: 'Diamonds 12',
    imageUrl: './assets/cards/card-diamonds-12.png',
    publicImageUrl: '/images/cards/card-diamonds-12.png',
  },
  {
    id: 47,
    name: 'Hearts 12',
    imageUrl: './assets/cards/card-hearts-12.png',
    publicImageUrl: '/images/cards/card-hearts-12.png',
  },
  {
    id: 48,
    name: 'Spades 12',
    imageUrl: './assets/cards/card-spades-12.png',
    publicImageUrl: '/images/cards/card-spades-12.png',
  },
  {
    id: 49,
    name: 'Clubs 13',
    imageUrl: './assets/cards/card-clubs-13.png',
    publicImageUrl: '/images/cards/card-clubs-13.png',
  },
  {
    id: 50,
    name: 'Diamonds 13',
    imageUrl: './assets/cards/card-diamonds-13.png',
    publicImageUrl: '/images/cards/card-diamonds-13.png',
  },
  {
    id: 51,
    name: 'Hearts 13',
    imageUrl: './assets/cards/card-hearts-13.png',
    publicImageUrl: '/images/cards/card-hearts-13.png',
  },
  {
    id: 52,
    name: 'Spades 13',
    imageUrl: './assets/cards/card-spades-13.png',
    publicImageUrl: '/images/cards/card-spades-13.png',
  },
];

export default cards;
